config/routes.rb
Rails.application.routes.draw do
  resources :excursaos
  resources :veiculos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excursao.rb
class Excursao < ApplicationRecord
belongs_to :veiculo

validates :nome, :partida, :chegada, :qtdveiculos, :destino, presence: true

end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  has_many :excursaos
  
  validates :nome, :limite_passageiro, :valor, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/excursaos_controller.rb
class ExcursaosController < ApplicationController
  skip_before_action :verify_authenticity_token

  # GET /excursaos
  # GET /excursaos.json
  def index
    excursaos = Excursao.all.map do |excursao| {
      id: excursao.id,
      nome: excursao.nome,
      created_at: excursao.created_at,
      partida: excursao.partida,
      chegada: excursao.chegada,
      veiculo: excursao.veiculo.nome,
      qtdveiculos: excursao.qtdveiculos,
      destino: excursao.destino,
      valorfinal: @valorfinal = excursao.veiculo.valor * excursao.veiculo.limite_passageiro * excursao.qtdveiculos,
      }
    end

    render status: :ok, json: excursaos
  end


  # POST /excursaos
  # POST /excursaos.json
  def create
    excursao = Excursao.new(excursaos_params)

    if excursao.save
      render status: :no_content, json: {}
    else
      render status: :bad_request, json: excursao.errors.messages
    end
  end

  def show
    @excursao = Excursao.find(params[:id])

    render status: :ok, json: @excursao
  end

  # PATCH/PUT /excursaos/1
  # PATCH/PUT /excursaos/1.json
  def update

    excursao = Excursao.find params[:id]
    
    if excursao.save excursaos_params
      render status: :no_content, json: {}
    else
      render status: :bad_request, json: excursao.errors.messages
    end
  end

  # DELETE /excursaos/1
  # DELETE /excursaos/1.json
  def destroy
    excursao = Excursao.find params[:id]

    if excursao.delete
      render status: :no_content, json: {}
    else
      render status: :bad_request, json: excursao.errors.messages
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def excursaos_params
      params.permit(:nome, :partida, :chegada, :veiculo_id, :qtdveiculos, :destino)
    end
end

app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    veiculos = Veiculo.all.order(:id)
    render status: :ok, json: veiculos
  end

  def show
    veiculo = Veiculo.find(params[:id])

    render status: :ok, json: veiculo
  end

  def create
    veiculo = Veiculo.new(veiculos_params)

    if veiculo.save
      render status: :no_content, json: {}
    else
      render status: :bad_request, json: veiculo.errors.messages
    end
  end

  def update
    veiculo = Veiculo.find params[:id]

    if veiculo.update veiculos_params
      render status: :no_content, json: {}
    else
      render status: :bad_request, json: veiculo.errors.messages
    end
  end

  private

  def veiculos_params
    #somente o que ira ser utilizado
    params.permit(:nome, :limite_passageiro, :valor)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/excursaos_helper.rb
module ExcursaosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/excursaos/_form.html.erb
<%= form_with(model: excursao, local: true) do |form| %>
  <% if excursao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(excursao.errors.count, "error") %> prohibited this excursao from being saved:</h2>

      <ul>
        <% excursao.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :partida %>
    <%= form.date_select :partida %>
  </div>

  <div class="field">
    <%= form.label :chegada %>
    <%= form.date_select :chegada %>
  </div>

  <div class="field">
    <%= form.label :qtdveiculos %>
    <%= form.number_field :qtdveiculos %>
  </div>

  <div class="field">
    <%= form.label :destino %>
    <%= form.text_field :destino %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/excursaos/edit.html.erb
<h1>Editing Excursao</h1>

<%= render 'form', excursao: @excursao %>

<%= link_to 'Show', @excursao %> |
<%= link_to 'Back', excursaos_path %>

app/views/excursaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Excursaos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Partida</th>
      <th>Chegada</th>
      <th>Qtdveiculos</th>
      <th>Destino</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @excursaos.each do |excursao| %>
      <tr>
        <td><%= excursao.nome %></td>
        <td><%= excursao.partida %></td>
        <td><%= excursao.chegada %></td>
        <td><%= excursao.qtdveiculos %></td>
        <td><%= excursao.destino %></td>
        <td><%= link_to 'Show', excursao %></td>
        <td><%= link_to 'Edit', edit_excursao_path(excursao) %></td>
        <td><%= link_to 'Destroy', excursao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Excursao', new_excursao_path %>

app/views/excursaos/new.html.erb
<h1>New Excursao</h1>

<%= render 'form', excursao: @excursao %>

<%= link_to 'Back', excursaos_path %>

app/views/excursaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @excursao.nome %>
</p>

<p>
  <strong>Partida:</strong>
  <%= @excursao.partida %>
</p>

<p>
  <strong>Chegada:</strong>
  <%= @excursao.chegada %>
</p>

<p>
  <strong>Qtdveiculos:</strong>
  <%= @excursao.qtdveiculos %>
</p>

<p>
  <strong>Destino:</strong>
  <%= @excursao.destino %>
</p>

<%= link_to 'Edit', edit_excursao_path(@excursao) %> |
<%= link_to 'Back', excursaos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExcursaoBackEnd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/veiculos/_form.html.erb
<%= form_with(model: veiculo, local: true) do |form| %>
  <% if veiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(veiculo.errors.count, "error") %> prohibited this veiculo from being saved:</h2>

      <ul>
        <% veiculo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :limite_passageiro %>
    <%= form.number_field :limite_passageiro %>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/veiculos/edit.html.erb
<h1>Editing Veiculo</h1>

<%= render 'form', veiculo: @veiculo %>

<%= link_to 'Show', @veiculo %> |
<%= link_to 'Back', veiculos_path %>

app/views/veiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Veiculos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Limite passageiro</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veiculos.each do |veiculo| %>
      <tr>
        <td><%= veiculo.nome %></td>
        <td><%= veiculo.limite_passageiro %></td>
        <td><%= veiculo.valor %></td>
        <td><%= link_to 'Show', veiculo %></td>
        <td><%= link_to 'Edit', edit_veiculo_path(veiculo) %></td>
        <td><%= link_to 'Destroy', veiculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Veiculo', new_veiculo_path %>

app/views/veiculos/new.html.erb
<h1>New Veiculo</h1>

<%= render 'form', veiculo: @veiculo %>

<%= link_to 'Back', veiculos_path %>

app/views/veiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @veiculo.nome %>
</p>

<p>
  <strong>Limite passageiro:</strong>
  <%= @veiculo.limite_passageiro %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @veiculo.valor %>
</p>

<%= link_to 'Edit', edit_veiculo_path(@veiculo) %> |
<%= link_to 'Back', veiculos_path %>